import AuthNavbar from '@/components/auth-navbar/AuthNavbar';
import "@/app/globals.css";

export const metadata = {
  title: 'Ecommerce Auth',
  description: 'Generated by Next.js',
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AuthNavbar />
        {children}
      </body>
    </html>
  )
}
